kind: pipeline
name: qt-5.12

steps:
- name: build and test
  image: nextcloudci/client-5.12:client-5.12-10
  commands:
    # Build client
    - /bin/bash -c "
      export CC=gcc-10 &&
      export CXX=g++-10 &&
      mkdir build &&
      cd build &&
      cmake -D NO_SHIBBOLETH=1 -DBUILD_UPDATER=ON -DCMAKE_BUILD_TYPE=Debug -DUNIT_TESTING=1 -DSANITIZE_ADDRESS=ON ../ &&
      make -j$(nproc) &&
      useradd -m -s /bin/bash test &&
      chown -R test:test . &&
      su -c 'ASAN_OPTIONS=detect_leaks=0 ctest --output-on-failure' test"
trigger:
  branch:
    - master
  event:
    - pull_request
    - push

---
kind: pipeline
name: qt-5.12-clang

steps:
- name: build and test
  image: nextcloudci/client-5.12:client-5.12-10
  commands:
    # Build client
    - /bin/bash -c "
      export CC=clang-10 &&
      export CXX=clang++-10 &&
      mkdir build &&
      cd build &&
      cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DNO_SHIBBOLETH=1 -DBUILD_UPDATER=ON -DCMAKE_BUILD_TYPE=Debug -DUNIT_TESTING=1 -DSANITIZE_ADDRESS=ON ../ &&
      make -j$(nproc) &&
      useradd -m -s /bin/bash test &&
      chown -R test:test . &&
      su -c 'ASAN_OPTIONS=detect_leaks=0 ctest --output-on-failure' test"
    # Static analysis with clang-tidy
    - "! run-clang-tidy-10 -p build -quiet | grep -A 5 ': error:'"
trigger:
  branch:
    - master
  event:
    - pull_request
    - push

---
kind: pipeline
name: AppImage

steps:
- name: build
  image: nextcloudci/client-5.12:client-5.12-10
  environment:
    CI_UPLOAD_GIT_TOKEN:
      from_secret: CI_UPLOAD_GIT_TOKEN
    CI_UPLOAD_GIT_USERNAME:
      from_secret: CI_UPLOAD_GIT_USERNAME
  commands:
    - /bin/bash -c "./admin/linux/build-appimage.sh"
    - /bin/bash -c "./admin/linux/upload-appimage.sh" || echo "Upload failed, however this is an optional step."
trigger:
  branch:
    - master
  event:
    - pull_request
    - push
---
kind: pipeline
name: Debian

steps:
- name: build
  image: nextcloudci/client-debian-ci:client-debian-ci-2
  commands:
    - /bin/bash -c "./admin/linux/debian/drone-build.sh"
  environment:
    DEBIAN_SECRET_KEY:
      from_secret: DEBIAN_SECRET_KEY
    DEBIAN_SECRET_IV:
      from_secret: DEBIAN_SECRET_IV
trigger:
  branch:
    - master
  event:
    - pull_request
    - push
---
kind: pipeline
name: Documentation

steps:
- name: build
  image: nextcloudci/documentation:documentation-5
  commands:
    - cd doc
    - make html
trigger:
  branch:
    - master
  event:
    - pull_request
    - push
